name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    services:
      influxdb:
        image: influxdb:2.8.0
        env:
          DOCKER_INFLUXDB_INIT_MODE: setup
          DOCKER_INFLUXDB_INIT_USERNAME: ci_user
          DOCKER_INFLUXDB_INIT_PASSWORD: password
          DOCKER_INFLUXDB_INIT_ORG: influxdata
          DOCKER_INFLUXDB_INIT_BUCKET: dummy
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: abcabc123123
        ports:
          - 8086
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black isort ruff
          python -m pip install .
      - name: Lint it
        run: |
          black --check .
          isort --profile black .
          ruff check
      - name: Install influx cli
        run: |
          wget https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.5-linux-amd64.tar.gz
          tar xvzf influxdb2-client-2.7.5-linux-amd64.tar.gz
          sudo cp influx /usr/local/bin/
      - name: Get an access token
        run: |
          influx config create --config-name influx-config \
            --host-url http://localhost:${{ job.services.influxdb.ports['8086'] }} \
            --org influxdata \
            --token abcabc123123\
            --active
          export INFLUXDB_TOKEN=$(influx auth create \
          --all-access \
          --host http://localhost:${{ job.services.influxdb.ports['8086'] }} \
          --org influxdata \
          --token abcabc123123 --json |jq '.token'| tr -d '"')
          echo "INFLUXDB_TOKEN=$INFLUXDB_TOKEN" >> $GITHUB_ENV
          echo HERE $INFLUXDB_TOKEN
      - name: Test with unittest
        run: |
          pip install ".[tests]"
          INFLUXDB_ORG=influxdata INFLUXDB_URL=http://localhost:${{ job.services.influxdb.ports['8086'] }} python -m unittest
